#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : geos
Version  : 3.12.2
Release  : 13
URL      : https://github.com/libgeos/geos/archive/3.12.2/geos-3.12.2.tar.gz
Source0  : https://github.com/libgeos/geos/archive/3.12.2/geos-3.12.2.tar.gz
Summary  : Geometry Engine, Open Source - C API
Group    : Development/Tools
License  : Apache-2.0 BSL-1.0 LGPL-2.1 MIT
Requires: geos-bin = %{version}-%{release}
Requires: geos-lib = %{version}-%{release}
Requires: geos-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : glibc-dev
BuildRequires : python3-dev
BuildRequires : swig
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
To build Doxygen documentation use:
make doxygen-html
Take a look at example.cpp to get started.

%package bin
Summary: bin components for the geos package.
Group: Binaries
Requires: geos-license = %{version}-%{release}

%description bin
bin components for the geos package.


%package dev
Summary: dev components for the geos package.
Group: Development
Requires: geos-lib = %{version}-%{release}
Requires: geos-bin = %{version}-%{release}
Provides: geos-devel = %{version}-%{release}
Requires: geos = %{version}-%{release}

%description dev
dev components for the geos package.


%package lib
Summary: lib components for the geos package.
Group: Libraries
Requires: geos-license = %{version}-%{release}

%description lib
lib components for the geos package.


%package license
Summary: license components for the geos package.
Group: Default

%description license
license components for the geos package.


%prep
%setup -q -n geos-3.12.2
cd %{_builddir}/geos-3.12.2
pushd ..
cp -a geos-3.12.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720028822
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720028822
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/geos
cp %{_builddir}/geos-%{version}/COPYING %{buildroot}/usr/share/package-licenses/geos/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/geos-%{version}/src/deps/ryu/LICENSE-Apache2 %{buildroot}/usr/share/package-licenses/geos/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/geos-%{version}/src/deps/ryu/LICENSE-Boost %{buildroot}/usr/share/package-licenses/geos/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/geos-%{version}/tools/astyle/LICENSE.md %{buildroot}/usr/share/package-licenses/geos/06f530aacebeb2c4056bf0caf66ad532bf1fa74e || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/geosop
/usr/bin/geos-config
/usr/bin/geosop

%files dev
%defattr(-,root,root,-)
/usr/include/geos.h
/usr/include/geos/algorithm/Angle.h
/usr/include/geos/algorithm/Area.h
/usr/include/geos/algorithm/BoundaryNodeRule.h
/usr/include/geos/algorithm/CGAlgorithmsDD.h
/usr/include/geos/algorithm/CentralEndpointIntersector.h
/usr/include/geos/algorithm/Centroid.h
/usr/include/geos/algorithm/ConvexHull.h
/usr/include/geos/algorithm/Distance.h
/usr/include/geos/algorithm/HCoordinate.h
/usr/include/geos/algorithm/InteriorPointArea.h
/usr/include/geos/algorithm/InteriorPointLine.h
/usr/include/geos/algorithm/InteriorPointPoint.h
/usr/include/geos/algorithm/Interpolate.h
/usr/include/geos/algorithm/Intersection.h
/usr/include/geos/algorithm/Length.h
/usr/include/geos/algorithm/LineIntersector.h
/usr/include/geos/algorithm/MinimumAreaRectangle.h
/usr/include/geos/algorithm/MinimumBoundingCircle.h
/usr/include/geos/algorithm/MinimumDiameter.h
/usr/include/geos/algorithm/NotRepresentableException.h
/usr/include/geos/algorithm/Orientation.h
/usr/include/geos/algorithm/PointInRing.h
/usr/include/geos/algorithm/PointLocation.h
/usr/include/geos/algorithm/PointLocator.h
/usr/include/geos/algorithm/PolygonNodeTopology.h
/usr/include/geos/algorithm/RayCrossingCounter.h
/usr/include/geos/algorithm/Rectangle.h
/usr/include/geos/algorithm/RobustDeterminant.h
/usr/include/geos/algorithm/SimplePointInRing.h
/usr/include/geos/algorithm/construct/LargestEmptyCircle.h
/usr/include/geos/algorithm/construct/MaximumInscribedCircle.h
/usr/include/geos/algorithm/distance/DiscreteFrechetDistance.h
/usr/include/geos/algorithm/distance/DiscreteHausdorffDistance.h
/usr/include/geos/algorithm/distance/DistanceToPoint.h
/usr/include/geos/algorithm/distance/PointPairDistance.h
/usr/include/geos/algorithm/hull/ConcaveHull.h
/usr/include/geos/algorithm/hull/ConcaveHullOfPolygons.h
/usr/include/geos/algorithm/hull/HullTri.h
/usr/include/geos/algorithm/hull/HullTriangulation.h
/usr/include/geos/algorithm/locate/IndexedPointInAreaLocator.h
/usr/include/geos/algorithm/locate/PointOnGeometryLocator.h
/usr/include/geos/algorithm/locate/SimplePointInAreaLocator.h
/usr/include/geos/constants.h
/usr/include/geos/coverage/Corner.h
/usr/include/geos/coverage/CoverageBoundarySegmentFinder.h
/usr/include/geos/coverage/CoverageEdge.h
/usr/include/geos/coverage/CoverageGapFinder.h
/usr/include/geos/coverage/CoveragePolygon.h
/usr/include/geos/coverage/CoveragePolygonValidator.h
/usr/include/geos/coverage/CoverageRing.h
/usr/include/geos/coverage/CoverageRingEdges.h
/usr/include/geos/coverage/CoverageSimplifier.h
/usr/include/geos/coverage/CoverageUnion.h
/usr/include/geos/coverage/CoverageValidator.h
/usr/include/geos/coverage/InvalidSegmentDetector.h
/usr/include/geos/coverage/TPVWSimplifier.h
/usr/include/geos/coverage/VertexRingCounter.h
/usr/include/geos/edgegraph/EdgeGraph.h
/usr/include/geos/edgegraph/EdgeGraphBuilder.h
/usr/include/geos/edgegraph/HalfEdge.h
/usr/include/geos/edgegraph/MarkHalfEdge.h
/usr/include/geos/export.h
/usr/include/geos/geom.h
/usr/include/geos/geom/Coordinate.h
/usr/include/geos/geom/CoordinateFilter.h
/usr/include/geos/geom/CoordinateList.h
/usr/include/geos/geom/CoordinateSequence.h
/usr/include/geos/geom/CoordinateSequenceFilter.h
/usr/include/geos/geom/CoordinateSequenceIterator.h
/usr/include/geos/geom/CoordinateSequences.h
/usr/include/geos/geom/Dimension.h
/usr/include/geos/geom/Envelope.h
/usr/include/geos/geom/Geometry.h
/usr/include/geos/geom/GeometryCollection.h
/usr/include/geos/geom/GeometryComponentFilter.h
/usr/include/geos/geom/GeometryFactory.h
/usr/include/geos/geom/GeometryFilter.h
/usr/include/geos/geom/HeuristicOverlay.h
/usr/include/geos/geom/IntersectionMatrix.h
/usr/include/geos/geom/LineSegment.h
/usr/include/geos/geom/LineString.h
/usr/include/geos/geom/LinearRing.h
/usr/include/geos/geom/Location.h
/usr/include/geos/geom/MultiLineString.h
/usr/include/geos/geom/MultiPoint.h
/usr/include/geos/geom/MultiPolygon.h
/usr/include/geos/geom/Point.h
/usr/include/geos/geom/Polygon.h
/usr/include/geos/geom/Position.h
/usr/include/geos/geom/PrecisionModel.h
/usr/include/geos/geom/Quadrant.h
/usr/include/geos/geom/Triangle.h
/usr/include/geos/geom/prep/AbstractPreparedPolygonContains.h
/usr/include/geos/geom/prep/BasicPreparedGeometry.h
/usr/include/geos/geom/prep/PreparedGeometry.h
/usr/include/geos/geom/prep/PreparedGeometryFactory.h
/usr/include/geos/geom/prep/PreparedLineString.h
/usr/include/geos/geom/prep/PreparedLineStringDistance.h
/usr/include/geos/geom/prep/PreparedLineStringIntersects.h
/usr/include/geos/geom/prep/PreparedLineStringNearestPoints.h
/usr/include/geos/geom/prep/PreparedPoint.h
/usr/include/geos/geom/prep/PreparedPolygon.h
/usr/include/geos/geom/prep/PreparedPolygonContains.h
/usr/include/geos/geom/prep/PreparedPolygonContainsProperly.h
/usr/include/geos/geom/prep/PreparedPolygonCovers.h
/usr/include/geos/geom/prep/PreparedPolygonDistance.h
/usr/include/geos/geom/prep/PreparedPolygonIntersects.h
/usr/include/geos/geom/prep/PreparedPolygonPredicate.h
/usr/include/geos/geom/util/ComponentCoordinateExtracter.h
/usr/include/geos/geom/util/CoordinateOperation.h
/usr/include/geos/geom/util/Densifier.h
/usr/include/geos/geom/util/GeometryCombiner.h
/usr/include/geos/geom/util/GeometryEditor.h
/usr/include/geos/geom/util/GeometryEditorOperation.h
/usr/include/geos/geom/util/GeometryExtracter.h
/usr/include/geos/geom/util/GeometryFixer.h
/usr/include/geos/geom/util/GeometryMapper.h
/usr/include/geos/geom/util/GeometryTransformer.h
/usr/include/geos/geom/util/LinearComponentExtracter.h
/usr/include/geos/geom/util/NoOpGeometryOperation.h
/usr/include/geos/geom/util/PointExtracter.h
/usr/include/geos/geom/util/PolygonExtracter.h
/usr/include/geos/geom/util/ShortCircuitedGeometryVisitor.h
/usr/include/geos/geom/util/SineStarFactory.h
/usr/include/geos/geomgraph/Depth.h
/usr/include/geos/geomgraph/DirectedEdge.h
/usr/include/geos/geomgraph/DirectedEdgeStar.h
/usr/include/geos/geomgraph/Edge.h
/usr/include/geos/geomgraph/EdgeEnd.h
/usr/include/geos/geomgraph/EdgeEndStar.h
/usr/include/geos/geomgraph/EdgeIntersection.h
/usr/include/geos/geomgraph/EdgeIntersectionList.h
/usr/include/geos/geomgraph/EdgeList.h
/usr/include/geos/geomgraph/EdgeNodingValidator.h
/usr/include/geos/geomgraph/EdgeRing.h
/usr/include/geos/geomgraph/GeometryGraph.h
/usr/include/geos/geomgraph/GraphComponent.h
/usr/include/geos/geomgraph/Label.h
/usr/include/geos/geomgraph/Node.h
/usr/include/geos/geomgraph/NodeFactory.h
/usr/include/geos/geomgraph/NodeMap.h
/usr/include/geos/geomgraph/PlanarGraph.h
/usr/include/geos/geomgraph/TopologyLocation.h
/usr/include/geos/geomgraph/index/EdgeSetIntersector.h
/usr/include/geos/geomgraph/index/MonotoneChain.h
/usr/include/geos/geomgraph/index/MonotoneChainEdge.h
/usr/include/geos/geomgraph/index/MonotoneChainIndexer.h
/usr/include/geos/geomgraph/index/SegmentIntersector.h
/usr/include/geos/geomgraph/index/SimpleEdgeSetIntersector.h
/usr/include/geos/geomgraph/index/SimpleMCSweepLineIntersector.h
/usr/include/geos/geomgraph/index/SimpleSweepLineIntersector.h
/usr/include/geos/geomgraph/index/SweepLineEvent.h
/usr/include/geos/geomgraph/index/SweepLineEventObj.h
/usr/include/geos/geomgraph/index/SweepLineSegment.h
/usr/include/geos/index/ItemVisitor.h
/usr/include/geos/index/SpatialIndex.h
/usr/include/geos/index/VertexSequencePackedRtree.h
/usr/include/geos/index/bintree/Bintree.h
/usr/include/geos/index/bintree/Interval.h
/usr/include/geos/index/bintree/Key.h
/usr/include/geos/index/bintree/Node.h
/usr/include/geos/index/bintree/NodeBase.h
/usr/include/geos/index/bintree/Root.h
/usr/include/geos/index/chain/MonotoneChain.h
/usr/include/geos/index/chain/MonotoneChainBuilder.h
/usr/include/geos/index/chain/MonotoneChainOverlapAction.h
/usr/include/geos/index/chain/MonotoneChainSelectAction.h
/usr/include/geos/index/intervalrtree/IntervalRTreeBranchNode.h
/usr/include/geos/index/intervalrtree/IntervalRTreeLeafNode.h
/usr/include/geos/index/intervalrtree/IntervalRTreeNode.h
/usr/include/geos/index/intervalrtree/SortedPackedIntervalRTree.h
/usr/include/geos/index/kdtree/KdNode.h
/usr/include/geos/index/kdtree/KdNodeVisitor.h
/usr/include/geos/index/kdtree/KdTree.h
/usr/include/geos/index/quadtree/IntervalSize.h
/usr/include/geos/index/quadtree/Key.h
/usr/include/geos/index/quadtree/Node.h
/usr/include/geos/index/quadtree/NodeBase.h
/usr/include/geos/index/quadtree/Quadtree.h
/usr/include/geos/index/quadtree/Root.h
/usr/include/geos/index/strtree/AbstractNode.h
/usr/include/geos/index/strtree/AbstractSTRtree.h
/usr/include/geos/index/strtree/Boundable.h
/usr/include/geos/index/strtree/BoundablePair.h
/usr/include/geos/index/strtree/EnvelopeUtil.h
/usr/include/geos/index/strtree/GeometryItemDistance.h
/usr/include/geos/index/strtree/Interval.h
/usr/include/geos/index/strtree/ItemBoundable.h
/usr/include/geos/index/strtree/ItemDistance.h
/usr/include/geos/index/strtree/SIRtree.h
/usr/include/geos/index/strtree/STRtree.h
/usr/include/geos/index/strtree/SimpleSTRdistance.h
/usr/include/geos/index/strtree/SimpleSTRnode.h
/usr/include/geos/index/strtree/SimpleSTRtree.h
/usr/include/geos/index/strtree/TemplateSTRNode.h
/usr/include/geos/index/strtree/TemplateSTRNodePair.h
/usr/include/geos/index/strtree/TemplateSTRtree.h
/usr/include/geos/index/strtree/TemplateSTRtreeDistance.h
/usr/include/geos/index/sweepline/SweepLineEvent.h
/usr/include/geos/index/sweepline/SweepLineIndex.h
/usr/include/geos/index/sweepline/SweepLineInterval.h
/usr/include/geos/index/sweepline/SweepLineOverlapAction.h
/usr/include/geos/io/ByteOrderDataInStream.h
/usr/include/geos/io/ByteOrderValues.h
/usr/include/geos/io/CLocalizer.h
/usr/include/geos/io/CheckOrdinatesFilter.h
/usr/include/geos/io/GeoJSON.h
/usr/include/geos/io/GeoJSONReader.h
/usr/include/geos/io/GeoJSONWriter.h
/usr/include/geos/io/OrdinateSet.h
/usr/include/geos/io/ParseException.h
/usr/include/geos/io/StringTokenizer.h
/usr/include/geos/io/WKBConstants.h
/usr/include/geos/io/WKBReader.h
/usr/include/geos/io/WKBStreamReader.h
/usr/include/geos/io/WKBWriter.h
/usr/include/geos/io/WKTFileReader.h
/usr/include/geos/io/WKTReader.h
/usr/include/geos/io/WKTStreamReader.h
/usr/include/geos/io/WKTWriter.h
/usr/include/geos/io/Writer.h
/usr/include/geos/linearref/ExtractLineByLocation.h
/usr/include/geos/linearref/LengthIndexOfPoint.h
/usr/include/geos/linearref/LengthIndexedLine.h
/usr/include/geos/linearref/LengthLocationMap.h
/usr/include/geos/linearref/LinearGeometryBuilder.h
/usr/include/geos/linearref/LinearIterator.h
/usr/include/geos/linearref/LinearLocation.h
/usr/include/geos/linearref/LocationIndexOfLine.h
/usr/include/geos/linearref/LocationIndexOfPoint.h
/usr/include/geos/linearref/LocationIndexedLine.h
/usr/include/geos/math/DD.h
/usr/include/geos/namespaces.h
/usr/include/geos/noding/BasicSegmentString.h
/usr/include/geos/noding/BoundaryChainNoder.h
/usr/include/geos/noding/FastNodingValidator.h
/usr/include/geos/noding/FastSegmentSetIntersectionFinder.h
/usr/include/geos/noding/GeometryNoder.h
/usr/include/geos/noding/IntersectionAdder.h
/usr/include/geos/noding/IntersectionFinderAdder.h
/usr/include/geos/noding/IteratedNoder.h
/usr/include/geos/noding/MCIndexNoder.h
/usr/include/geos/noding/MCIndexSegmentSetMutualIntersector.h
/usr/include/geos/noding/NodableSegmentString.h
/usr/include/geos/noding/NodedSegmentString.h
/usr/include/geos/noding/Noder.h
/usr/include/geos/noding/NodingIntersectionFinder.h
/usr/include/geos/noding/NodingValidator.h
/usr/include/geos/noding/Octant.h
/usr/include/geos/noding/OrientedCoordinateArray.h
/usr/include/geos/noding/ScaledNoder.h
/usr/include/geos/noding/SegmentExtractingNoder.h
/usr/include/geos/noding/SegmentIntersectionDetector.h
/usr/include/geos/noding/SegmentIntersector.h
/usr/include/geos/noding/SegmentNode.h
/usr/include/geos/noding/SegmentNodeList.h
/usr/include/geos/noding/SegmentPointComparator.h
/usr/include/geos/noding/SegmentSetMutualIntersector.h
/usr/include/geos/noding/SegmentString.h
/usr/include/geos/noding/SegmentStringUtil.h
/usr/include/geos/noding/SimpleNoder.h
/usr/include/geos/noding/SinglePassNoder.h
/usr/include/geos/noding/ValidatingNoder.h
/usr/include/geos/noding/snap/SnappingIntersectionAdder.h
/usr/include/geos/noding/snap/SnappingNoder.h
/usr/include/geos/noding/snap/SnappingPointIndex.h
/usr/include/geos/noding/snapround/HotPixel.h
/usr/include/geos/noding/snapround/HotPixelIndex.h
/usr/include/geos/noding/snapround/MCIndexPointSnapper.h
/usr/include/geos/noding/snapround/MCIndexSnapRounder.h
/usr/include/geos/noding/snapround/SnapRoundingIntersectionAdder.h
/usr/include/geos/noding/snapround/SnapRoundingNoder.h
/usr/include/geos/operation/BoundaryOp.h
/usr/include/geos/operation/GeometryGraphOperation.h
/usr/include/geos/operation/buffer/BufferBuilder.h
/usr/include/geos/operation/buffer/BufferCurveSetBuilder.h
/usr/include/geos/operation/buffer/BufferInputLineSimplifier.h
/usr/include/geos/operation/buffer/BufferOp.h
/usr/include/geos/operation/buffer/BufferParameters.h
/usr/include/geos/operation/buffer/BufferSubgraph.h
/usr/include/geos/operation/buffer/OffsetCurve.h
/usr/include/geos/operation/buffer/OffsetCurveBuilder.h
/usr/include/geos/operation/buffer/OffsetCurveSection.h
/usr/include/geos/operation/buffer/OffsetSegmentGenerator.h
/usr/include/geos/operation/buffer/OffsetSegmentString.h
/usr/include/geos/operation/buffer/RightmostEdgeFinder.h
/usr/include/geos/operation/buffer/SegmentMCIndex.h
/usr/include/geos/operation/buffer/SubgraphDepthLocater.h
/usr/include/geos/operation/cluster/AbstractClusterFinder.h
/usr/include/geos/operation/cluster/Clusters.h
/usr/include/geos/operation/cluster/DBSCANClusterFinder.h
/usr/include/geos/operation/cluster/DisjointOperation.h
/usr/include/geos/operation/cluster/EnvelopeDistanceClusterFinder.h
/usr/include/geos/operation/cluster/EnvelopeIntersectsClusterFinder.h
/usr/include/geos/operation/cluster/GeometryDistanceClusterFinder.h
/usr/include/geos/operation/cluster/GeometryFlattener.h
/usr/include/geos/operation/cluster/GeometryIntersectsClusterFinder.h
/usr/include/geos/operation/cluster/UnionFind.h
/usr/include/geos/operation/distance/ConnectedElementLocationFilter.h
/usr/include/geos/operation/distance/ConnectedElementPointFilter.h
/usr/include/geos/operation/distance/DistanceOp.h
/usr/include/geos/operation/distance/FacetSequence.h
/usr/include/geos/operation/distance/FacetSequenceTreeBuilder.h
/usr/include/geos/operation/distance/GeometryLocation.h
/usr/include/geos/operation/distance/IndexedFacetDistance.h
/usr/include/geos/operation/intersection/Rectangle.h
/usr/include/geos/operation/intersection/RectangleIntersection.h
/usr/include/geos/operation/intersection/RectangleIntersectionBuilder.h
/usr/include/geos/operation/linemerge/EdgeString.h
/usr/include/geos/operation/linemerge/LineMergeDirectedEdge.h
/usr/include/geos/operation/linemerge/LineMergeEdge.h
/usr/include/geos/operation/linemerge/LineMergeGraph.h
/usr/include/geos/operation/linemerge/LineMerger.h
/usr/include/geos/operation/linemerge/LineSequencer.h
/usr/include/geos/operation/overlay/MaximalEdgeRing.h
/usr/include/geos/operation/overlay/MinimalEdgeRing.h
/usr/include/geos/operation/overlay/OverlayNodeFactory.h
/usr/include/geos/operation/overlay/PolygonBuilder.h
/usr/include/geos/operation/overlay/snap/GeometrySnapper.h
/usr/include/geos/operation/overlay/snap/LineStringSnapper.h
/usr/include/geos/operation/overlay/snap/SnapOverlayOp.h
/usr/include/geos/operation/overlay/validate/FuzzyPointLocator.h
/usr/include/geos/operation/overlay/validate/OffsetPointGenerator.h
/usr/include/geos/operation/overlay/validate/OverlayResultValidator.h
/usr/include/geos/operation/overlayng/CoverageUnion.h
/usr/include/geos/operation/overlayng/Edge.h
/usr/include/geos/operation/overlayng/EdgeKey.h
/usr/include/geos/operation/overlayng/EdgeMerger.h
/usr/include/geos/operation/overlayng/EdgeNodingBuilder.h
/usr/include/geos/operation/overlayng/EdgeSourceInfo.h
/usr/include/geos/operation/overlayng/ElevationModel.h
/usr/include/geos/operation/overlayng/IndexedPointOnLineLocator.h
/usr/include/geos/operation/overlayng/InputGeometry.h
/usr/include/geos/operation/overlayng/IntersectionPointBuilder.h
/usr/include/geos/operation/overlayng/LineBuilder.h
/usr/include/geos/operation/overlayng/LineLimiter.h
/usr/include/geos/operation/overlayng/MaximalEdgeRing.h
/usr/include/geos/operation/overlayng/OverlayEdge.h
/usr/include/geos/operation/overlayng/OverlayEdgeRing.h
/usr/include/geos/operation/overlayng/OverlayGraph.h
/usr/include/geos/operation/overlayng/OverlayLabel.h
/usr/include/geos/operation/overlayng/OverlayLabeller.h
/usr/include/geos/operation/overlayng/OverlayMixedPoints.h
/usr/include/geos/operation/overlayng/OverlayNG.h
/usr/include/geos/operation/overlayng/OverlayNGRobust.h
/usr/include/geos/operation/overlayng/OverlayPoints.h
/usr/include/geos/operation/overlayng/OverlayUtil.h
/usr/include/geos/operation/overlayng/PolygonBuilder.h
/usr/include/geos/operation/overlayng/PrecisionReducer.h
/usr/include/geos/operation/overlayng/PrecisionUtil.h
/usr/include/geos/operation/overlayng/RingClipper.h
/usr/include/geos/operation/overlayng/RobustClipEnvelopeComputer.h
/usr/include/geos/operation/overlayng/UnaryUnionNG.h
/usr/include/geos/operation/polygonize/BuildArea.h
/usr/include/geos/operation/polygonize/EdgeRing.h
/usr/include/geos/operation/polygonize/HoleAssigner.h
/usr/include/geos/operation/polygonize/PolygonizeDirectedEdge.h
/usr/include/geos/operation/polygonize/PolygonizeEdge.h
/usr/include/geos/operation/polygonize/PolygonizeGraph.h
/usr/include/geos/operation/polygonize/Polygonizer.h
/usr/include/geos/operation/predicate/RectangleContains.h
/usr/include/geos/operation/predicate/RectangleIntersects.h
/usr/include/geos/operation/predicate/SegmentIntersectionTester.h
/usr/include/geos/operation/relate/EdgeEndBuilder.h
/usr/include/geos/operation/relate/EdgeEndBundle.h
/usr/include/geos/operation/relate/EdgeEndBundleStar.h
/usr/include/geos/operation/relate/RelateComputer.h
/usr/include/geos/operation/relate/RelateNode.h
/usr/include/geos/operation/relate/RelateNodeFactory.h
/usr/include/geos/operation/relate/RelateNodeGraph.h
/usr/include/geos/operation/relate/RelateOp.h
/usr/include/geos/operation/sharedpaths/SharedPathsOp.h
/usr/include/geos/operation/union/CascadedPolygonUnion.h
/usr/include/geos/operation/union/CoverageUnion.h
/usr/include/geos/operation/union/DisjointSubsetUnion.h
/usr/include/geos/operation/union/OverlapUnion.h
/usr/include/geos/operation/union/PointGeometryUnion.h
/usr/include/geos/operation/union/UnaryUnionOp.h
/usr/include/geos/operation/union/UnionStrategy.h
/usr/include/geos/operation/valid/ConsistentAreaTester.h
/usr/include/geos/operation/valid/IndexedNestedHoleTester.h
/usr/include/geos/operation/valid/IndexedNestedPolygonTester.h
/usr/include/geos/operation/valid/IsSimpleOp.h
/usr/include/geos/operation/valid/IsValidOp.h
/usr/include/geos/operation/valid/MakeValid.h
/usr/include/geos/operation/valid/PolygonIntersectionAnalyzer.h
/usr/include/geos/operation/valid/PolygonRing.h
/usr/include/geos/operation/valid/PolygonRingSelfNode.h
/usr/include/geos/operation/valid/PolygonRingTouch.h
/usr/include/geos/operation/valid/PolygonTopologyAnalyzer.h
/usr/include/geos/operation/valid/RepeatedPointRemover.h
/usr/include/geos/operation/valid/RepeatedPointTester.h
/usr/include/geos/operation/valid/TopologyValidationError.h
/usr/include/geos/planargraph/DirectedEdge.h
/usr/include/geos/planargraph/DirectedEdgeStar.h
/usr/include/geos/planargraph/Edge.h
/usr/include/geos/planargraph/GraphComponent.h
/usr/include/geos/planargraph/Node.h
/usr/include/geos/planargraph/NodeMap.h
/usr/include/geos/planargraph/PlanarGraph.h
/usr/include/geos/planargraph/Subgraph.h
/usr/include/geos/planargraph/algorithm/ConnectedSubgraphFinder.h
/usr/include/geos/precision/CommonBits.h
/usr/include/geos/precision/CommonBitsOp.h
/usr/include/geos/precision/CommonBitsRemover.h
/usr/include/geos/precision/EnhancedPrecisionOp.h
/usr/include/geos/precision/GeometryPrecisionReducer.h
/usr/include/geos/precision/MinimumClearance.h
/usr/include/geos/precision/PointwisePrecisionReducerTransformer.h
/usr/include/geos/precision/PrecisionReducerCoordinateOperation.h
/usr/include/geos/precision/PrecisionReducerTransformer.h
/usr/include/geos/precision/SimpleGeometryPrecisionReducer.h
/usr/include/geos/profiler.h
/usr/include/geos/shape/fractal/HilbertCode.h
/usr/include/geos/shape/fractal/HilbertEncoder.h
/usr/include/geos/shape/fractal/MortonCode.h
/usr/include/geos/simplify/ComponentJumpChecker.h
/usr/include/geos/simplify/DouglasPeuckerLineSimplifier.h
/usr/include/geos/simplify/DouglasPeuckerSimplifier.h
/usr/include/geos/simplify/LineSegmentIndex.h
/usr/include/geos/simplify/LinkedLine.h
/usr/include/geos/simplify/LinkedRing.h
/usr/include/geos/simplify/PolygonHullSimplifier.h
/usr/include/geos/simplify/RingHull.h
/usr/include/geos/simplify/RingHullIndex.h
/usr/include/geos/simplify/TaggedLineSegment.h
/usr/include/geos/simplify/TaggedLineString.h
/usr/include/geos/simplify/TaggedLineStringSimplifier.h
/usr/include/geos/simplify/TaggedLinesSimplifier.h
/usr/include/geos/simplify/TopologyPreservingSimplifier.h
/usr/include/geos/triangulate/DelaunayTriangulationBuilder.h
/usr/include/geos/triangulate/IncrementalDelaunayTriangulator.h
/usr/include/geos/triangulate/VoronoiDiagramBuilder.h
/usr/include/geos/triangulate/polygon/ConstrainedDelaunayTriangulator.h
/usr/include/geos/triangulate/polygon/PolygonEarClipper.h
/usr/include/geos/triangulate/polygon/PolygonHoleJoiner.h
/usr/include/geos/triangulate/polygon/PolygonNoder.h
/usr/include/geos/triangulate/polygon/PolygonTriangulator.h
/usr/include/geos/triangulate/polygon/TriDelaunayImprover.h
/usr/include/geos/triangulate/quadedge/LastFoundQuadEdgeLocator.h
/usr/include/geos/triangulate/quadedge/LocateFailureException.h
/usr/include/geos/triangulate/quadedge/QuadEdge.h
/usr/include/geos/triangulate/quadedge/QuadEdgeLocator.h
/usr/include/geos/triangulate/quadedge/QuadEdgeQuartet.h
/usr/include/geos/triangulate/quadedge/QuadEdgeSubdivision.h
/usr/include/geos/triangulate/quadedge/TrianglePredicate.h
/usr/include/geos/triangulate/quadedge/TriangleVisitor.h
/usr/include/geos/triangulate/quadedge/Vertex.h
/usr/include/geos/triangulate/tri/Tri.h
/usr/include/geos/triangulate/tri/TriEdge.h
/usr/include/geos/triangulate/tri/TriList.h
/usr/include/geos/triangulate/tri/TriangulationBuilder.h
/usr/include/geos/unload.h
/usr/include/geos/util.h
/usr/include/geos/util/Assert.h
/usr/include/geos/util/AssertionFailedException.h
/usr/include/geos/util/CoordinateArrayFilter.h
/usr/include/geos/util/GEOSException.h
/usr/include/geos/util/GeometricShapeFactory.h
/usr/include/geos/util/IllegalArgumentException.h
/usr/include/geos/util/IllegalStateException.h
/usr/include/geos/util/Interrupt.h
/usr/include/geos/util/Machine.h
/usr/include/geos/util/TopologyException.h
/usr/include/geos/util/UniqueCoordinateArrayFilter.h
/usr/include/geos/util/UnsupportedOperationException.h
/usr/include/geos/util/math.h
/usr/include/geos/util/string.h
/usr/include/geos/vend/include_nlohmann_json.hpp
/usr/include/geos/vend/json.hpp
/usr/include/geos/version.h
/usr/include/geos_c.h
/usr/lib64/cmake/GEOS/geos-config-version.cmake
/usr/lib64/cmake/GEOS/geos-config.cmake
/usr/lib64/cmake/GEOS/geos-targets-relwithdebinfo.cmake
/usr/lib64/cmake/GEOS/geos-targets.cmake
/usr/lib64/pkgconfig/geos.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libgeos.so.3.12.2
/V3/usr/lib64/libgeos_c.so.1.18.2
/usr/lib64/libgeos.so
/usr/lib64/libgeos.so.3.12.2
/usr/lib64/libgeos_c.so
/usr/lib64/libgeos_c.so.1
/usr/lib64/libgeos_c.so.1.18.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/geos/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/geos/06f530aacebeb2c4056bf0caf66ad532bf1fa74e
/usr/share/package-licenses/geos/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/geos/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
